#!/bin/bash
printf "\n\e[0;32m🍣   Uglifying Elm...\e[0m\n\n"
node_modules/.bin/uglifyjs docs/js/elm.v.1.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | node_modules/.bin/uglifyjs --mangle --output=docs/js/elm.v.1.min.js
node_modules/.bin/uglifyjs docs/js/elm.v.2.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | node_modules/.bin/uglifyjs --mangle --output=docs/js/elm.v.2.min.js
